### ISSUE TITLE
Action types export format

### ISSUE THREAD

**Issue by maxbarbul** [SergioV85/learning-react-app#1]
It would be cleaner to export action types using `default`, in that case you'll be able to import it as a file without additional level of object:

```javascript
enum MovieDetailsActionTypes { /* ... */ }

// somewhere in other file
// also, note there is no need in './../' you can just use '../'
import MovieDetailsActionTypes from '../action-types/movie-details.action-types'

// ...
type = MovieDetailsActionTypes.GetMovie
```

**Comment by SergioV85** [comment]
Ok, thanks! I will update it today.

**Comment by SergioV85** [comment]
Updated (see commit for details). Also, I had to update unit-tests, because I found, that it is a common issue with ts-jest (TypeScript compiler for Jest). TS-Jest can't compile enums in test (see https://github.com/kulshekhar/ts-jest#const-enum-is-not-supported).
