### ISSUE TITLE
Task 3: decomposition part

### ISSUE THREAD

**Issue by maxbarbul** [SergioV85/learning-react-app#2]
I'd like you to split(decompose) components a bit more. Though, it's currently enough from the perspective of current implementation, the task is to have decomposition enogh for imaginary growing app and it should be ready for frther changes. In this case, smaller components would play better.

Please decompose the following components:

1. status bar: toggle buttons, button group label, sort buttons with label(label could be used as a component).
1. search pannel: use components extracted from status bar
1. movie list: extract `empty list` component
1. movie card and details certainly share some pieces. Would be nice to extract title, poster, genre, raiting, year.

**Comment by SergioV85** [comment]
Ok, thanks! I will update it today.

**Comment by SergioV85** [comment]
Done
