### ISSUE TITLE
Task 5 issues

### ISSUE THREAD

**Issue by maxbarbul** [SergioV85/learning-react-app#4]
So far, great job, reducers are great, actions are as well.

Though, to have 5 stars:

1. reducers are not enough covered
1. Local storage is not used as far as I see

Also, it's not reuired, though I think would be natural to show the movie list at the first open. For now it shows "empty list" message.

**Comment by SergioV85** [comment]
Yes, it not finished completely yet. I will finish it today/tomorrow.

**Comment by SergioV85** [comment]
Updated unit-tests and configured offline storing of Redux store
